// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDucb_y29Jd85XEgCsl0ltESOq3DAPup5w',
    appId: '1:663254852197:web:3cd64bf8b1692530821c8c',
    messagingSenderId: '663254852197',
    projectId: 'gymhive-656cb',
    authDomain: 'gymhive-656cb.firebaseapp.com',
    storageBucket: 'gymhive-656cb.appspot.com',
    measurementId: 'G-B5C0L8KHGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJPocpqBnKUQtjoQhx8Kk81JEMN9-Kvg',
    appId: '1:663254852197:android:3a49b26f65e285a8821c8c',
    messagingSenderId: '663254852197',
    projectId: 'gymhive-656cb',
    storageBucket: 'gymhive-656cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6S2sE0N2Uyc76kqfUL--jClBdIZx-nRQ',
    appId: '1:663254852197:ios:5214ba5203c05d0a821c8c',
    messagingSenderId: '663254852197',
    projectId: 'gymhive-656cb',
    storageBucket: 'gymhive-656cb.appspot.com',
    iosBundleId: 'com.example.sihGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6S2sE0N2Uyc76kqfUL--jClBdIZx-nRQ',
    appId: '1:663254852197:ios:9958a2c0da24e48d821c8c',
    messagingSenderId: '663254852197',
    projectId: 'gymhive-656cb',
    storageBucket: 'gymhive-656cb.appspot.com',
    iosBundleId: 'com.example.sihGym.RunnerTests',
  );
}
