// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIWDpGKCOqODZTC19naGkbISSWu7uIxe4',
    appId: '1:835254322475:web:25f6b33d1cc66dddf7716e',
    messagingSenderId: '835254322475',
    projectId: 'sih-gym',
    authDomain: 'sih-gym.firebaseapp.com',
    storageBucket: 'sih-gym.appspot.com',
    measurementId: 'G-DKFSEDHJLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_GLROeONbud5358QwBbxR1Iq2LH971M',
    appId: '1:835254322475:android:e66fc276c3a0420bf7716e',
    messagingSenderId: '835254322475',
    projectId: 'sih-gym',
    storageBucket: 'sih-gym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJEFUkfjx6gH5tloIqbofSj9ouHocei0',
    appId: '1:835254322475:ios:90faf3cd43718c09f7716e',
    messagingSenderId: '835254322475',
    projectId: 'sih-gym',
    storageBucket: 'sih-gym.appspot.com',
    iosBundleId: 'com.example.sihGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChJEFUkfjx6gH5tloIqbofSj9ouHocei0',
    appId: '1:835254322475:ios:e1814a2fe0475a59f7716e',
    messagingSenderId: '835254322475',
    projectId: 'sih-gym',
    storageBucket: 'sih-gym.appspot.com',
    iosBundleId: 'com.example.sihGym.RunnerTests',
  );
}
